FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install uv
RUN uv pip install --system -r requirements.txt

COPY . .

CMD alembic upgrade head && uvicorn backend.api.main:app --host 0.0.0.0 --port ${PORT:-8000}
