"""Initial schema

Revision ID: 9d701427dc2b
Revises: 
Create Date: 2026-08-19 06:00:04.919764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d701427dc2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_areas',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('opportunity_title', sa.String(), nullable=False),
    sa.Column('opportunity_description', sa.String(), nullable=False),
    sa.Column('source_theme_ids', sa.JSON(), nullable=True),
    sa.Column('supporting_observation_count', sa.Integer(), nullable=False),
    sa.Column('pct_of_relevant_observations', sa.Float(), nullable=True),
    sa.Column('source_distribution', sa.JSON(), nullable=True),
    sa.Column('myntra_specific_count', sa.Integer(), nullable=True),
    sa.Column('category_level_count', sa.Integer(), nullable=True),
    sa.Column('associated_wishlist_intents', sa.JSON(), nullable=True),
    sa.Column('associated_purchase_intents', sa.JSON(), nullable=True),
    sa.Column('associated_segments', sa.JSON(), nullable=True),
    sa.Column('recurring_root_causes', sa.JSON(), nullable=True),
    sa.Column('recurring_uncertainties', sa.JSON(), nullable=True),
    sa.Column('recurring_info_needs', sa.JSON(), nullable=True),
    sa.Column('recurring_workarounds', sa.JSON(), nullable=True),
    sa.Column('external_research_behaviors', sa.JSON(), nullable=True),
    sa.Column('avg_evidence_confidence', sa.Float(), nullable=True),
    sa.Column('representative_quotes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_window_start', sa.Date(), nullable=True),
    sa.Column('review_window_end', sa.Date(), nullable=True),
    sa.Column('source_statuses', sa.JSON(), nullable=True),
    sa.Column('source_record_counts', sa.JSON(), nullable=True),
    sa.Column('relevant_record_count', sa.Integer(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('theme_count', sa.Integer(), nullable=True),
    sa.Column('opportunity_count', sa.Integer(), nullable=True),
    sa.Column('provider_model_versions', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('raw_records',
    sa.Column('raw_record_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('product_context', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('parent_post_id', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('video_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('raw_record_id')
    )
    op.create_table('themes',
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('theme_name', sa.String(), nullable=False),
    sa.Column('theme_label', sa.String(), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('pct_of_relevant', sa.Float(), nullable=True),
    sa.Column('common_root_causes', sa.JSON(), nullable=True),
    sa.Column('associated_wishlist_intents', sa.JSON(), nullable=True),
    sa.Column('associated_purchase_intents', sa.JSON(), nullable=True),
    sa.Column('affected_segments', sa.JSON(), nullable=True),
    sa.Column('recurring_uncertainties', sa.JSON(), nullable=True),
    sa.Column('recurring_info_needs', sa.JSON(), nullable=True),
    sa.Column('common_workarounds', sa.JSON(), nullable=True),
    sa.Column('external_research_behaviors', sa.JSON(), nullable=True),
    sa.Column('representative_quotes', sa.JSON(), nullable=True),
    sa.Column('source_distribution', sa.JSON(), nullable=True),
    sa.Column('myntra_specific_count', sa.Integer(), nullable=True),
    sa.Column('category_level_count', sa.Integer(), nullable=True),
    sa.Column('avg_ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('theme_id')
    )
    op.create_table('cleaned_records',
    sa.Column('cleaned_record_id', sa.String(), nullable=False),
    sa.Column('raw_record_id', sa.String(), nullable=False),
    sa.Column('cleaned_text', sa.String(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('cleaning_flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('cleaned_record_id')
    )
    op.create_table('dataset_stats',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('raw_record_count', sa.Integer(), nullable=True),
    sa.Column('cleaned_record_count', sa.Integer(), nullable=True),
    sa.Column('pct_cleaned', sa.Float(), nullable=True),
    sa.Column('relevant_count', sa.Integer(), nullable=True),
    sa.Column('pct_relevant', sa.Float(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('avg_observations_per_record', sa.Float(), nullable=True),
    sa.Column('avg_ai_confidence', sa.Float(), nullable=True),
    sa.Column('low_confidence_observation_count', sa.Integer(), nullable=True),
    sa.Column('extraction_failure_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('run_records',
    sa.Column('run_record_id', sa.String(), nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=False),
    sa.Column('raw_record_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.run_id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('run_record_id')
    )
    op.create_table('classified_records',
    sa.Column('classified_record_id', sa.String(), nullable=False),
    sa.Column('cleaned_record_id', sa.String(), nullable=False),
    sa.Column('relevance_label', sa.String(), nullable=False),
    sa.Column('relevance_confidence', sa.Float(), nullable=False),
    sa.Column('signals_detected', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cleaned_record_id'], ['cleaned_records.cleaned_record_id'], ),
    sa.PrimaryKeyConstraint('classified_record_id')
    )
    op.create_table('observations',
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('cleaned_record_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_myntra_specific', sa.Boolean(), nullable=True),
    sa.Column('journey_stage', sa.String(), nullable=True),
    sa.Column('wishlist_intent', sa.String(), nullable=True),
    sa.Column('purchase_intent', sa.String(), nullable=True),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('primary_barrier', sa.String(), nullable=True),
    sa.Column('secondary_barriers', sa.JSON(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('uncertainty', sa.String(), nullable=True),
    sa.Column('information_needed', sa.String(), nullable=True),
    sa.Column('workaround', sa.String(), nullable=True),
    sa.Column('external_platform_used', sa.String(), nullable=True),
    sa.Column('alternative_considered', sa.String(), nullable=True),
    sa.Column('occasion', sa.String(), nullable=True),
    sa.Column('decision_outcome', sa.String(), nullable=True),
    sa.Column('segment_signal', sa.String(), nullable=True),
    sa.Column('evidence_quote', sa.String(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('created_in_pipeline_run_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cleaned_record_id'], ['cleaned_records.cleaned_record_id'], ),
    sa.ForeignKeyConstraint(['created_in_pipeline_run_id'], ['pipeline_runs.run_id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['raw_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('opportunity_observations',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.observation_id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity_areas.opportunity_id'], ),
    sa.PrimaryKeyConstraint('opportunity_id', 'observation_id')
    )
    op.create_table('theme_observations',
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.observation_id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.theme_id'], ),
    sa.PrimaryKeyConstraint('theme_id', 'observation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_observations')
    op.drop_table('opportunity_observations')
    op.drop_table('observations')
    op.drop_table('classified_records')
    op.drop_table('run_records')
    op.drop_table('dataset_stats')
    op.drop_table('cleaned_records')
    op.drop_table('themes')
    op.drop_table('raw_records')
    op.drop_table('pipeline_runs')
    op.drop_table('opportunity_areas')
    # ### end Alembic commands ###
